image: node:8

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run build
    - npm test

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
